### PR TITLE
Introduce poetry with linters

### PR DESCRIPTION
**Pull request by kdiri**
🎨 
* Define new way of lib dependency management: Poetry (It is still optional)
* Introduce black and mypy linters (They are still optionals)
* Black the code
* Move test to tests directory
* Tests are failing, I don't get why. Can you help ? (It's ok now)

## TODO for the next time: 
* Be able to manage two versions of python (36, 38)
* Run tests using poetry 
* Instead of hard coding dependencies in setup.py, use poetry install
* Docker

### CODE REVIEW

**Comment by benjhar** [comment]
Can you tell me what the failure is? Tests are also failing for me, I just want to make sure it's consistent between us.

**Comment by kdiri** [comment]
My principal error is related to absence of `token` env variable. As I don't have it, tests are failing. If I call the method without `auth_token` parameter :

```python
j.get_joke(category=["programming"]) # auth_token=token is removed
```
All is well. 


Otherwise, there is another error (the miscellaneous category is unknown that's why the test fails.):

```python
j.get_joke(category=["miscellaneous"]) # auth_token=token is removed
```

Screenshot 2021-01-05 at 12 13 15

**Comment by benjhar** [comment]
Tests should not fail if your `token` is equal to `None`, what are you setting the `token` variable as/what does `getenv("token")` return for you? As for the category error, I am about to push a commit that fixes that.

**Comment by kdiri** [comment]
Effectively. Tests are passing (except miscellaneous) even `getenv("token")` returns `None`.

**Comment by benjhar** [comment]
I have pushed a commit that fixes the miscellaneous category test, if you pull that you should be error free if I'm interpreting you correctly.

**Comment by kdiri** [comment]
Can you please tell me if you agree with the modifications or should I rollback the PR ? :)

**Comment by benjhar** [comment]
Apologies, I somewhat forgot about this PR, merging.

**Comment by kdiri** [comment]
Thanks 🙂

**Pull request merged**
